version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/spring-boot-tdd

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          key: spring-boot-tdd-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-tdd-{{ checksum "pom.xml" }}
      - run: mvn clean test
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build-test:
    jobs:
      - build
